apiVersion: 1

deleteDatasources:
  - name: Prometheus

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://prometheus:9090
  isDefault: true
  version: 1
  editable: true
- name: RRD
  type: graphite
  access: proxy
  url: http://graphiterrd:9180
  isDefault: false
  editable: true